# daemonless metadata and cit config
icon: ':material-television:'

cit:
  port: 8989
  health: /ping
  annotations:
    - org.freebsd.jail.allow.mlock=true

build:
  variants:
    - tag: latest
      containerfile: Containerfile
      default: true
    - tag: pkg
      containerfile: Containerfile.pkg
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
